[package]
name = "to_csv"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
debug = false
incremental = false
strip = true
panic = "abort"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
encoding_rs = "0.8"